language: python
python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.4"

install:
  - pip install codecov tox
script:
  - tox --
after_success:
  - codecov
env:
  - TOXENV=py27-django111
  - TOXENV=py34-django111
  - TOXENV=py35-django111
  - TOXENV=py36-django111

  - TOXENV=py34-django20
  - TOXENV=py35-django20
  - TOXENV=py36-django20

  - TOXENV=isort
